_target_: src.logger.WandBWriter
project_name: "asr_deepspeech"
entity: null
run_name: "AdamW3e-4Cos_instAugs"
mode: "online"
loss_names: ["loss"] # which losses to log (useful for multi-loss tasks, s.a. GANs)
log_checkpoints: True # set to True if you want to log save_dir with checkpoints to W&B
id_length: 8 # length of the run_id
